def get_llc_village():
    villages = ["Port Pirie Lifestyle Village", "Fairway Rise Lifestyle Village", "Ingenia Lifestyle Stoney Creek",
                "Wyee Point Lifestyle Community", "Lifestyle Geelong", "Lifestyle Mount Duneed",
                "Avondale Lifestyle Community", "Jewells Lifestyle Community", "Lifestyle Shepparton",
                "Sugar Valley Lifestyle Estate", "Lifestyle Kaduna Park", "Greenbank Gardens Lifestyle resort",
                "Eureka Gainsborough Lifestyle Village", "Tweed Heads Lifestyle Community",
                "Waterbrook Retirement Lifestyle Resort", "Pepperfield Lifestyle Resort Bowral",
                "Wattle Grove Community Lifestyle", "The Sands Lifestyle Community", "Ingenia Lifestyle Mudgee",
                "Lifestyle Seasons", "Lifestyle Merrifield", "Lifestyle Manor",
                "Ingenia Lifestyle Lakeside Lara, Greater Geelong", "Kangaroo Flat Lifestyle Estate by Lincoln Place",
                "Lifestyle Lyndarum", "Lifestyle Bittern", "Lifestyle Berwick Waters", "Lifestyle Brookfield",
                "Ingenia Lifestyle Parkside Lucas", "The Rose Lifestyle Village",
                "Baranduda Lifestyle Estate by Lincoln Place", "Lifestyle Yarrawonga", "Lifestyle Officer",
                "The Parks Lifestyle Community", "Lifestyle Ridgelea", "Lifestyle Villages Traralgon",
                "Greenacres Lifestyle Coast & County", "Peninsula Lifestyle Retirement Village", "Lifestyle Hastings",
                "Lifestyle Phillip Island", "Heysen Court Lifestyle Community", "Lifestyle Casey Fields",
                "Moonta Bay Lifestyle Estate", "Frenchview Lifestyle Village", "Golden Downs Lifestyle Community",
                "Ingenia Lifestyle Chambers Pines, Brisbane", "Ingenia Lifestyle Bethania",
                "Lewani Palms Over50's Lifestyle Resort", "The Henley on Broadwater Lifestyle Resort",
                "The Springs Lifestyle Village", "Lifestyle Warragul",
                "Freshwater by Ingenia Lifestyle, Burpengary East, Brisbane",
                "Silver Shores Lifestyle Estate by Lincoln Place", "The Ferns Lifestyle Community",
                "Nambucca River Lifestyle Estate by Lincoln Place", "Ingenia Lifestyle Hervey Bay",
                "Parklands Lifestyle Village", "The Anchorage Lifestyle Resort", "Lifestyle Villages Bundaberg",
                "Ingenia Lifestyle Vineyard", "Heritage Gardens Lifestyle Village", "Botanica Lifestyle Resort",
                "Thyme Lifestyle Resort Mareeba", "Savannah Lifestyle Resorts", "Lifestyle Chelsea Heights",
                "Lucas Lifestyle Estate", "Huntly Lifestyle Estate by Lincoln Place", "The Vines Lifestyle Community",
                "Lifestyle Bellarine", "Lifestyle Ocean Grove", "Lifestyle Deanside", "Bendigo Lifestyle Village",
                "Lifestyle Wollert", "Forest Place Lifestyle Community", "The Elms Lifestyle Community",
                "The Gardens Lifestyle Community", "Evanston Lifestyle", "Golden Grove Lifestyle Community",
                "Mudgee Spring Lifestyle Estate by Lincoln Place", "Officer Lifestyle Estate by Lincoln Place",
                "Lifestyle Meridian", "Waikerie Lifestyle Village", "Copper Coast Lifestyle Village",
                "The Reserve Lifestyle Community", "Vasse Lifestyle Village", "Karrinyup Lakes Lifestyle Village",
                "Portland Lifestyle Estate by Lincoln Place", "Lifestyle Woodlea",
                "Helena Valley National Lifestyle Villages", "Lake Joondalup National Lifestyle Village",
                "Pineview National Lifestyle Village", "Thyme Lifestyle Resort Moreton Bay",
                "Sunshine Park Lifestyle Village", "RV Lifestyle Village Oceanside", "Forest Lakes Lifestyle Village",
                "Champion Lakes Lifestyle Village", "Vibe Baldivis Lifestyle Village", "Tuart Lakes Lifestyle Village",
                "Belswan Lifestyle Village Pinjarra", "National Lifestyle Villages - Bridgewater",
                "Belswan Lifestyle Village Mandurah", "Meadowbrooke Lifestyle Estate",
                "Busselton National Lifestyle Village", "Margaret River Lifestyle Village",
                "Oyster Harbour National Lifestyle Village", "Clarence Lifestyle Village",
                "Thyme Lifestyle Resort Hervey Bay", "Drift By Ingenia Lifestyle, Bargara",
                "Nambucca Heads Lifestyle Estate", "Ingenia Lifestyle Middle Rock", "Ingenia Lifestyle Coastal Palms",
                "The Links Over 55 Lifestyle Resort", "Mt Barker Lifestyle Community"]
    return villages
