def get_brisbane_tags() -> list:
    tags = [
        "BCC Compliance Assessment;|Acid sulphate soils management plan;",
        "BCC Compliance Assessment;|Air quality management plan;",
        "BCC Compliance Assessment;|Architectural Assessment;",
        "BCC Compliance Assessment;|Area Adjoining a Heritage Place;",
        "BCC Compliance Assessment;|Biodiversity Offsets;",
        "BCC Compliance Assessment;|Bulk Earthworks;",
        "BCC Compliance Assessment;|Bushfire Management;",
        "BCC Compliance Assessment;|Car Parking Management Plan;",
        "BCC Compliance Assessment;|Construction Management Plans;",
        "BCC Compliance Assessment;|Detailed Design Signalised Intersections;",
        "BCC Compliance Assessment;|Environmental Management Assessment;",
        "BCC Compliance Assessment;|Environmental Management Plan;",
        "BCC Compliance Assessment;|Erosion and Sediment Control;",
        "BCC Compliance Assessment;|External Materials and Finishes;",
        "BCC Compliance Assessment;|Fauna Management;",
        "BCC Compliance Assessment;|Filling and/or Excavation;",
        "BCC Compliance Assessment;|Hazard and risk assessment plan;",
        "BCC Compliance Assessment;|Heritage Place - Adjoining (Op Work);",
        "BCC Compliance Assessment;|Heritage Place (LHP);",
        "BCC Compliance Assessment;|Heritage Place (Op Work);",
        "BCC Compliance Assessment;|Heritage Place (QHP);",
        "BCC Compliance Assessment;|Koala Offsets;",
        "BCC Compliance Assessment;|Landscape Works in Park;",
        "BCC Compliance Assessment;|Landscape Works in Streetscape;",
        "BCC Compliance Assessment;|Landscape Works on Private Land;",
        "BCC Compliance Assessment;|Local Heritage Place;",
        "BCC Compliance Assessment;|Major Infrastructure Item;",
        "BCC Compliance Assessment;|Natural Environment Assessment;",
        "BCC Compliance Assessment;|Noise/Dust Management;",
        "BCC Compliance Assessment;|Prescribed Tidal Work;",
        "BCC Compliance Assessment;|Rehabilitation Plan;",
        "BCC Compliance Assessment;|Road Works and/or Stormwater Drainage;",
        "BCC Compliance Assessment;|Roadworks;",
        "BCC Compliance Assessment;|Signs and Line Marking for Major Roads;",
        "BCC Compliance Assessment;|Signs and Line Marking for Minor Roads;",
        "BCC Compliance Assessment;|Signs and Line Marking for Signalised Intersections;",
        "BCC Compliance Assessment;|Site Based Stormwater Quality Management Plan;",
        "BCC Compliance Assessment;|Site Based Stormwater Quantity Management Plan;",
        "BCC Compliance Assessment;|State Heritage Place;",
        "BCC Compliance Assessment;|Stormwater Drainage;",
        "BCC Compliance Assessment;|Street Naming and Numbering;",
        "BCC Compliance Assessment;|Sustainability Management;",
        "BCC Compliance Assessment;|Traffic Functional Layout for Major Roads;",
        "BCC Compliance Assessment;|Traffic Functional Layout for Minor Roads;",
        "BCC Compliance Assessment;|Vegetation Management Plan;",
        "BCC Compliance Assessment;|Wind Impacts;",
        "Build Over or Near Stormwater;|Build Over or Near Stormwater;",
        "Build Over Sewer;|Build Over Sewer;",
        "Building Over or Near Stormwater;|Build Over or Near Stormwater;",
        "Commercial;|Adult Store;",
        "Commercial;|Agricultural Supplies Store;",
        "Commercial;|Air Services;",
        "Commercial;|Amusement Arcade;",
        "Commercial;|Animal Husbandry;",
        "Commercial;|Animal Keeping;",
        "Commercial;|Aquaculture;",
        "Commercial;|Area Adjoining a Heritage Place;",
        "Commercial;|Awnings Over Footpath;",
        "Commercial;|Bar;",
        "Commercial;|Brothel;",
        "Commercial;|Bulk Landscape Supplies;",
        "Commercial;|Car Park;",
        "Commercial;|Car Wash;",
        "Commercial;|Caretakers Accommodation;",
        "Commercial;|Caretaker's Accommodation;",
        "Commercial;|Carpark;",
        "Commercial;|Cattery;",
        "Commercial;|Centre Activity Outside Centre;",
        "Commercial;|Centre Activity Within Centre;",
        "Commercial;|Centre Activity;",
        "Commercial;|Centres Concept Plan;",
        "Commercial;|Child Care Centre;",
        "Commercial;|Child Care Facility;",
        "Commercial;|Cinema;",
        "Commercial;|Club;",
        "Commercial;|Commercial Character Building - Demolition;",
        "Commercial;|Commercial Character Building - Extension;",
        "Commercial;|Commercial Character Building - Partial Demolition;",
        "Commercial;|Commercial Character Building (Activity Within);",
        "Commercial;|Commercial Character Building (Demolition/Extension);",
        "Commercial;|Commercial Character Building Activity;",
        "Commercial;|Community Care Centre;",
        "Commercial;|Community Residence;",
        "Commercial;|Community Use;",
        "Commercial;|Convention Centre ;",
        "Commercial;|Convention Centre;",
        "Commercial;|Crematorium;",
        "Commercial;|Cropping;",
        "Commercial;|Demolition/Extension to Heritage Place;",
        "Commercial;|Demolition;",
        "Commercial;|Detention Facility;",
        "Commercial;|Display and Sale Activities;",
        "Commercial;|Display Dwelling;",
        "Commercial;|Dual Occupancy;",
        "Commercial;|Dwelling House - 3 Storey House;",
        "Commercial;|Dwelling House - over 9.5m;",
        "Commercial;|Dwelling House;",
        "Commercial;|Dwelling Unit;",
        "Commercial;|Educational Establishment;",
        "Commercial;|Environment Facility;",
        "Commercial;|Environmentally Relevant Activity;",
        "Commercial;|Estate Sales Office;",
        "Commercial;|Extension;",
        "Commercial;|Facade Alterations (Mall);",
        "Commercial;|Farm;",
        "Commercial;|Filling and Excavation;",
        "Commercial;|Food and Drink Outlet;",
        "Commercial;|Function Facility;",
        "Commercial;|Funeral Parlour;",
        "Commercial;|Garden Centre;",
        "Commercial;|Hardware and Trade Supplies;",
        "Commercial;|Health Care Purposes;",
        "Commercial;|Health Care Service;",
        "Commercial;|Health Care Services;",
        "Commercial;|Heritage Place - Adjoining (Building Work);",
        "Commercial;|Heritage Place - Demolition;",
        "Commercial;|Heritage Place - Extension;",
        "Commercial;|Heritage Place - Partial Demolition;",
        "Commercial;|Heritage Place (LHP);",
        "Commercial;|Heritage Place (QHP);",
        "Commercial;|High Impact Industry;",
        "Commercial;|Home Based Business;",
        "Commercial;|Home Business;",
        "Commercial;|Hospital;",
        "Commercial;|Hotel;",
        "Commercial;|Intensive Animal Industry;",
        "Commercial;|Intensive horticulture;",
        "Commercial;|Intensive Horticulture;",
        "Commercial;|Kennels;",
        "Commercial;|Landing;",
        "Commercial;|Local Heritage Place;",
        "Commercial;|Low Impact Industry;",
        "Commercial;|Major Electricity Infrastructure;",
        "Commercial;|Major Sport, Recreation and Entertainment Facility;",
        "Commercial;|Marine Industry;",
        "Commercial;|Market;",
        "Commercial;|Medical Centre;",
        "Commercial;|Medium Impact Industry;",
        "Commercial;|Mixed Use;",
        "Commercial;|Motor Sport Facility;",
        "Commercial;|Multiple Dwelling;",
        "Commercial;|Nature Based Tourism;",
        "Commercial;|Nature-based Tourism;",
        "Commercial;|Nightclub Entertainment Facility;",
        "Commercial;|Nightclub;",
        "Commercial;|Non-Resident Worker;",
        "Commercial;|Non-resident workforce accommodation;",
        "Commercial;|Non-Resident Workforce Accommodation;",
        "Commercial;|Office;",
        "Commercial;|Outdoor Sales;",
        "Commercial;|Parking Station;",
        "Commercial;|Particular Development;",
        "Commercial;|Permanent Plantation;",
        "Commercial;|Place of Worship;",
        "Commercial;|Port Service;",
        "Commercial;|Port Services;",
        "Commercial;|Radio or Television Station;",
        "Commercial;|Relocatable Home Park;",
        "Commercial;|Renewable Energy Facility;",
        "Commercial;|Research and Technology Industry;",
        "Commercial;|Residential Care Facility;",
        "Commercial;|Resort Complex;",
        "Commercial;|Restaurant;",
        "Commercial;|Retirement Facility;",
        "Commercial;|Riding School;",
        "Commercial;|Roadside Stall;",
        "Commercial;|Rooming Accommodation;",
        "Commercial;|Rural Industry;",
        "Commercial;|Rural Worker Accommodation;",
        "Commercial;|Rural Workers Accommodation;",
        "Commercial;|Sales Office;",
        "Commercial;|Satellite Dish;",
        "Commercial;|Service Industry;",
        "Commercial;|Service Station;",
        "Commercial;|Shop;",
        "Commercial;|Shopping Centre;",
        "Commercial;|Short-term Accommodation;",
        "Commercial;|Short-Term Accommodation;",
        "Commercial;|Showroom;",
        "Commercial;|Special Industry;",
        "Commercial;|Stable;",
        "Commercial;|Stables;",
        "Commercial;|State Heritage Place;",
        "Commercial;|Structure Plan;",
        "Commercial;|Substation;",
        "Commercial;|Telecommunication Tower;",
        "Commercial;|Telecommunications Facility;",
        "Commercial;|Theatre;",
        "Commercial;|Tourist Attraction;",
        "Commercial;|Tourist Park;",
        "Commercial;|Transport Depot;",
        "Commercial;|Utility Installation;",
        "Commercial;|Veterinary Facility;",
        "Commercial;|Veterinary Service;",
        "Commercial;|Veterinary Services;",
        "Commercial;|Veterinary Surgery;",
        "Commercial;|Wholesale Nursery;",
        "Commercial;|Winery;",
        "Engineering;|Architectural Assessment;",
        "Engineering;|Area Adjoining a Heritage Place;",
        "Engineering;|Biodiversity Offsets;",
        "Engineering;|Build Over Sewer;",
        "Engineering;|Build Over Stormwater;",
        "Engineering;|Bulk Earthworks;",
        "Engineering;|Bushfire Management;",
        "Engineering;|Car Parking Management Plan;",
        "Engineering;|Construction Management Plans;",
        "Engineering;|Detailed Design Signalised Intersections;",
        "Engineering;|Environmental Management Assessment;",
        "Engineering;|Erosion and Sediment Control;",
        "Engineering;|External Materials and Finishes;",
        "Engineering;|Fauna Management;",
        "Engineering;|Filling and Excavation (Retaining walls and BBQ area);",
        "Engineering;|Filling and Excavation;",
        "Engineering;|Filling and/or Excavation;",
        "Engineering;|Hazard and risk assessment plan;",
        "Engineering;|Heritage Place - Adjoining (Op Work);",
        "Engineering;|Heritage Place (LHP);",
        "Engineering;|Heritage Place (Op Work);",
        "Engineering;|Heritage Place (QHP);",
        "Engineering;|Koala Offsets;",
        "Engineering;|Local Heritage Place;",
        "Engineering;|Major Infrastructure Design Item;",
        "Engineering;|Major Infrastructure Design Plans;",
        "Engineering;|Major Infrastructure Item;",
        "Engineering;|Natural Environment Assessment;",
        "Engineering;|Offset Management;",
        "Engineering;|Prescribed Tidal Work;",
        "Engineering;|Road Works and/or Stomwater Drainage;",
        "Engineering;|Road Works and/or Stormwater Drainage;",
        "Engineering;|Roadworks and/or Drainage;",
        "Engineering;|Roadworks;",
        "Engineering;|Sewerage Reticulation;",
        "Engineering;|Signs and Line Marking for Major Roads;",
        "Engineering;|Signs and Line Marking for Minor Roads;",
        "Engineering;|Signs and Line Marking for Signalised Intersections;",
        "Engineering;|Signs and Line Marking for Type A, B or C Roads;",
        "Engineering;|Signs and Line Marking for Type D Roads or Signalised Intersections;",
        "Engineering;|Site Based Stormwater Quantity Management Plan;",
        "Engineering;|State Heritage Place;",
        "Engineering;|Stormwater Drainage;",
        "Engineering;|Street Naming and Numbering;",
        "Engineering;|Sustainability Management;",
        "Engineering;|Tidal Work;",
        "Engineering;|Traffic Functional Layout for Major Roads;",
        "Engineering;|Traffic Functional Layout for Minor Roads;",
        "Engineering;|Traffic Functional Layout for Type A, B, or C Roads;",
        "Engineering;|Traffic Functional Layout for Type D Roads or Signalised Intersection;",
        "Engineering;|Trunk Sewer;",
        "Engineering;|Trunk Water;",
        "Engineering;|Water Reticulation;",
        "Engineering;|Wind Impacts;",
        "Environmentally Relevant Activities;|ERA 12(1) - Plastic product manufacturing;",
        "Environmentally Relevant Activities;|ERA 12(2) - Plastic product manufacturing;",
        "Environmentally Relevant Activities;|ERA 19 - Metal forming;",
        "Environmentally Relevant Activities;|ERA 20(1) - Metal recovery;",
        "Environmentally Relevant Activities;|ERA 20(2)(a) - Metal recovery;",
        "Environmentally Relevant Activities;|ERA 38(1)(a) - Surface coating;",
        "Environmentally Relevant Activities;|ERA 49 - Boat maintenance or repair carried out at a boat maintenance or repair facility;",
        "Environmentally Relevant Activities;|ERA 6 - Asphalt manufacturing;",
        "Environmentally Relevant Activities;|ERA 61(1) - Waste incineration and thermal treatment;",
        "Exemption Certificate;|Access Easement;",
        "Exemption Certificate;|Adult Store;",
        "Exemption Certificate;|Aged Care Accommodation (Multiple Dwelling);",
        "Exemption Certificate;|Aged Care Accommodation (Multi-unit Dwelling);",
        "Exemption Certificate;|Agricultural Supplies Store;",
        "Exemption Certificate;|Air Services;",
        "Exemption Certificate;|Amusement Arcade;",
        "Exemption Certificate;|Animal Husbandry;",
        "Exemption Certificate;|Animal Keeping;",
        "Exemption Certificate;|Aquaculture;",
        "Exemption Certificate;|Awnings Over Footpath;",
        "Exemption Certificate;|Bar;",
        "Exemption Certificate;|Boundary Realignment;",
        "Exemption Certificate;|Brothel;",
        "Exemption Certificate;|Building Format Plan;",
        "Exemption Certificate;|Bulk Landscape Supplies;",
        "Exemption Certificate;|Busway;",
        "Exemption Certificate;|Camping Ground;",
        "Exemption Certificate;|Car Wash;",
        "Exemption Certificate;|Caravan Park;",
        "Exemption Certificate;|Caretakers Accommodation;",
        "Exemption Certificate;|Caretakers Flat;",
        "Exemption Certificate;|Carpark;",
        "Exemption Certificate;|Cattery;",
        "Exemption Certificate;|Cemetery;",
        "Exemption Certificate;|Centre Activity;",
        "Exemption Certificate;|Child Care Centre;",
        "Exemption Certificate;|Child Care Facility;",
        "Exemption Certificate;|Cinema;",
        "Exemption Certificate;|Club;",
        "Exemption Certificate;|Commercial Character Building - Demolition;",
        "Exemption Certificate;|Commercial Character Building - Partial Demolition;",
        "Exemption Certificate;|Community Care Centre;",
        "Exemption Certificate;|Community Facilities;",
        "Exemption Certificate;|Community Residence;",
        "Exemption Certificate;|Community Use;",
        "Exemption Certificate;|Concrete Batching Plant ;",
        "Exemption Certificate;|Container Depot;",
        "Exemption Certificate;|Convention Centre;",
        "Exemption Certificate;|Crematorium;",
        "Exemption Certificate;|Cropping;",
        "Exemption Certificate;|Demolition;",
        "Exemption Certificate;|Detention Facility;",
        "Exemption Certificate;|Display Dwelling;",
        "Exemption Certificate;|Dual Occupancy;",
        "Exemption Certificate;|Dwelling House - 3 Storey House;",
        "Exemption Certificate;|Dwelling House - over 9.5m;",
        "Exemption Certificate;|Dwelling House;",
        "Exemption Certificate;|Dwelling Unit;",
        "Exemption Certificate;|Education Purposes ;",
        "Exemption Certificate;|Educational Establishment;",
        "Exemption Certificate;|Emergency Services;",
        "Exemption Certificate;|Environment Facility;",
        "Exemption Certificate;|Extension;",
        "Exemption Certificate;|Extractive Industry;",
        "Exemption Certificate;|Facade Alterations (Mall);",
        "Exemption Certificate;|Food and Drink Outlet;",
        "Exemption Certificate;|Function Facility;",
        "Exemption Certificate;|Funeral Parlour;",
        "Exemption Certificate;|Garden Centre;",
        "Exemption Certificate;|Hardware and Trade Supplies;",
        "Exemption Certificate;|Health Care Service;",
        "Exemption Certificate;|Heritage Place - Adjoining (Building Work);",
        "Exemption Certificate;|Heritage Place - Demolition;",
        "Exemption Certificate;|Heritage Place - Extension;",
        "Exemption Certificate;|Heritage Place - Partial Demolition;",
        "Exemption Certificate;|Heritage Place (LHP);",
        "Exemption Certificate;|Heritage Place (QHP);",
        "Exemption Certificate;|High Impact Industry;",
        "Exemption Certificate;|Home Based Business;",
        "Exemption Certificate;|Hospital;",
        "Exemption Certificate;|Hotel;",
        "Exemption Certificate;|House - Extension;",
        "Exemption Certificate;|House - Other;",
        "Exemption Certificate;|House in a Waterway Corridor;",
        "Exemption Certificate;|House in DCP - Demolition;",
        "Exemption Certificate;|House in DCP - Partial Demolition;",
        "Exemption Certificate;|House in DCP;",
        "Exemption Certificate;|House in EP/Rural Area;",
        "Exemption Certificate;|House in Pre-1911;",
        "Exemption Certificate;|House in TBC - Demolition;",
        "Exemption Certificate;|House in TBC - Partial Demolition;",
        "Exemption Certificate;|House in TBC;",
        "Exemption Certificate;|House On Small Lot;",
        "Exemption Certificate;|House over 8.5m;",
        "Exemption Certificate;|Indoor Sport and Recreation;",
        "Exemption Certificate;|Industry;",
        "Exemption Certificate;|Intensive Animal Industry;",
        "Exemption Certificate;|Intensive Horticulture;",
        "Exemption Certificate;|Kennels;",
        "Exemption Certificate;|Landing;",
        "Exemption Certificate;|Light Rail;",
        "Exemption Certificate;|Low Impact Industry;",
        "Exemption Certificate;|Major Electricity Infrastructure;",
        "Exemption Certificate;|Major Sport, Recreation and Entertainment Facility;",
        "Exemption Certificate;|Marine Industry;",
        "Exemption Certificate;|Market;",
        "Exemption Certificate;|Medical Centre;",
        "Exemption Certificate;|Medium Impact Industry;",
        "Exemption Certificate;|Motor Sport Facility;",
        "Exemption Certificate;|Multiple Dwelling;",
        "Exemption Certificate;|Multi-Unit Dwelling;",
        "Exemption Certificate;|Nature-based Tourism;",
        "Exemption Certificate;|Nightclub Entertainment Facility;",
        "Exemption Certificate;|Non-Resident Worker;",
        "Exemption Certificate;|Office;",
        "Exemption Certificate;|Outdoor Sales;",
        "Exemption Certificate;|Outdoor Sport and Recreation;",
        "Exemption Certificate;|Park;",
        "Exemption Certificate;|Parking Station;",
        "Exemption Certificate;|Permanent Plantation;",
        "Exemption Certificate;|Place of Worship;",
        "Exemption Certificate;|Port Service;",
        "Exemption Certificate;|Radio or Television Station;",
        "Exemption Certificate;|Radioactive Industry;",
        "Exemption Certificate;|Railway Activities;",
        "Exemption Certificate;|Relocatable Home Park;",
        "Exemption Certificate;|Renewable Energy Facility;",
        "Exemption Certificate;|Research and Technology Industry;",
        "Exemption Certificate;|Residential Care Facility;",
        "Exemption Certificate;|Resort Complex;",
        "Exemption Certificate;|Retirement Facility;",
        "Exemption Certificate;|Retirement Village (Multi-unit Dwelling);",
        "Exemption Certificate;|Riding School;",
        "Exemption Certificate;|Road;",
        "Exemption Certificate;|Roadside Stall;",
        "Exemption Certificate;|Rooming Accommodation;",
        "Exemption Certificate;|Rural Industry;",
        "Exemption Certificate;|Rural Worker Accommodation;",
        "Exemption Certificate;|Sales Office;",
        "Exemption Certificate;|Satellite Dish;",
        "Exemption Certificate;|Service Industry;",
        "Exemption Certificate;|Service Station;",
        "Exemption Certificate;|Shop;",
        "Exemption Certificate;|Shopping Centre;",
        "Exemption Certificate;|Short Term Accommodation;",
        "Exemption Certificate;|Short-Term Accommodation;",
        "Exemption Certificate;|Showroom;",
        "Exemption Certificate;|Single Unit Dwelling;",
        "Exemption Certificate;|Special Industry;",
        "Exemption Certificate;|Special Needs (Multi-unit Dwelling);",
        "Exemption Certificate;|Standard Format Plan;",
        "Exemption Certificate;|Structure Plan;",
        "Exemption Certificate;|Subdivision by Lease;",
        "Exemption Certificate;|Subdivision of Land;",
        "Exemption Certificate;|Substation;",
        "Exemption Certificate;|Telecommunications Facility;",
        "Exemption Certificate;|Theatre;",
        "Exemption Certificate;|Tourist Attraction;",
        "Exemption Certificate;|Tourist Park;",
        "Exemption Certificate;|Transport Depot;",
        "Exemption Certificate;|Utility Installation;",
        "Exemption Certificate;|Veterinary Service;",
        "Exemption Certificate;|Veterinary Surgery;",
        "Exemption Certificate;|Volumetric Subdivision;",
        "Exemption Certificate;|Warehouse;",
        "Exemption Certificate;|Wholesale Nursery;",
        "Exemption Certificate;|Winery;",
        "Exemption Certificate;|Youth Club",
        "Exemption Certificate;|Demolition of a pre-1946 building (other than a House);",
        "Exemption Certificate;|Demolition/Extension to Heritage Place (residential dwelling);",
        "Exemption Certificate;|Display Home;",
        "Exemption Certificate;|Heritage Place (Residential Dwelling) - Demolition;",
        "Exemption Certificate;|Heritage Place (Residential Dwelling) - Extension;",
        "Exemption Certificate;|Heritage Place (Residential Dwelling) - Partial Demolition;",
        "Exemption Certificate;|Home Based Business;",
        "Exemption Certificate;|Home Business;",
        "Exemption Certificate;|House - Extension;",
        "Exemption Certificate;|House - Other;",
        "Exemption Certificate;|House in a Waterway Corridor;",
        "Exemption Certificate;|House in DCP - Demolition;",
        "Exemption Certificate;|House in DCP - Partial Demolition;",
        "Exemption Certificate;|House in DCP (Demolition/Extension);",
        "Exemption Certificate;|House in DCP;",
        "Exemption Certificate;|House in EP/Rural Area;",
        "Exemption Certificate;|House in Pre-1911;",
        "Exemption Certificate;|House in TBC - Demolition;",
        "Exemption Certificate;|House in TBC - Partial Demolition;",
        "Exemption Certificate;|House in TBC;",
        "Exemption Certificate;|House On Small Lot;",
        "Exemption Certificate;|House over 8.5m;",
        "Exemption Certificate;|Landing (Residential - Domestic);",
        "Exemption Certificate;|Non-Compliant With House Code;",
        "Exemption Certificate;|Outdoor Lighting;",
        "Industry;|Concrete Batching Plant ;",
        "Industry;|Concrete Batching Plant;",
        "Industry;|Container Depot;",
        "Industry;|Extractive Industry ;",
        "Industry;|Extractive Industry;",
        "Industry;|Industry;",
        "Industry;|Radioactive Industry;",
        "Industry;|Storage Yard;",
        "Industry;|Warehouse;",
        "Natural Environment;|Architectural Assessment;",
        "Natural Environment;|External Materials and Finishes;",
        "Natural Environment;|Landscape Works in Park;",
        "Natural Environment;|Landscape Works in Streetscape;",
        "Natural Environment;|Landscape Works on Private Land ;",
        "Natural Environment;|Landscape Works on Private Land;",
        "Natural Environment;|Rehabilitation Plan;",
        "Natural Environment;|Site Based Stormwater Quality Management Plan;",
        "Natural Environment;|Sustainability;",
        "Natural Environment;|Vegetation Management Plan;",
        "Plan Sealing;|Access easement;",
        "Plan Sealing;|Building Format Plan;",
        "Plan Sealing;|Community Management Plan;",
        "Plan Sealing;|Community Management Statement;",
        "Plan Sealing;|Covenant;",
        "Plan Sealing;|Easement Plan;",
        "Plan Sealing;|Easement;",
        "Plan Sealing;|Lease Plan;",
        "Plan Sealing;|Standard Format Plan;",
        "Plan Sealing;|Survey Plan;",
        "Plan Sealing;|Volumetric Plan;",
        "Pollution;|Acid sulphate soils management plan;",
        "Pollution;|Air quality management plan;",
        "Pollution;|Environmental Management Plan;",
        "Pollution;|Noise/Dust Management;",
        "Reconfiguration;|1 into 2 Reconfiguration of a Lot;",
        "Reconfiguration;|Plan Sealing",
        "Reconfiguration;|Access Easement;",
        "Reconfiguration;|Area Adjoining a Heritage Place;",
        "Reconfiguration;|Boundary Realignment;",
        "Reconfiguration;|Building Format Plan;",
        "Reconfiguration;|Heritage Place - Adjoining (ROL);",
        "Reconfiguration;|Heritage Place (LHP);",
        "Reconfiguration;|Heritage Place (QHP);",
        "Reconfiguration;|Heritage Place (ROL);",
        "Reconfiguration;|Local Heritage Place;",
        "Reconfiguration;|Particular Development;",
        "Reconfiguration;|Standard Format Plan;",
        "Reconfiguration;|State Heritage Place;",
        "Reconfiguration;|Structure Plan;",
        "Reconfiguration;|Subdivision by Lease;",
        "Reconfiguration;|Subdivision of Land;",
        "Reconfiguration;|Volumetric Subdivision;",
        "Referral Agency for Building Work;|Amenity and aesthetics;",
        "Referral Agency for Building Work;|Design and siting;",
        "Referral Agency for Building Work;|Dwelling House - Extension (small lot);",
        "Referral Agency for Building Work;|Dwelling House - Extension;",
        "Referral Agency for Building Work;|Dwelling House - Traditional Building Character;",
        "Referral Agency for Building Work;|Dwelling House (small lot);",
        "Referral Agency for Building Work;|Dwelling House;",
        "Referral Agency for Building Work;|Flood hazard area;",
        "Referral Agency for Building Work;|Local heritage place;",
        "Referral Agency;|Council as a Referral Agency to assessable development;",
        "Residential - Domestic;|Demolition of a pre-1946 building (other than a House);",
        "Residential - Domestic;|Demolition/Extension to Heritage Place (residential dwelling);",
        "Residential - Domestic;|Display Home;",
        "Residential - Domestic;|Heritage Place (Residential Dwelling) - Demolition;",
        "Residential - Domestic;|Heritage Place (Residential Dwelling) - Extension;",
        "Residential - Domestic;|Heritage Place (Residential Dwelling) - Partial Demolition;",
        "Residential - Domestic;|Home Business;",
        "Residential - Domestic;|House in a Waterway Corridor;",
        "Residential - Domestic;|House in DCP - Demolition;",
        "Residential - Domestic;|House in DCP - Extension;",
        "Residential - Domestic;|House in DCP - Partial Demolition;",
        "Residential - Domestic;|House in DCP (Demolition/Extension);",
        "Residential - Domestic;|House in DCP (New House);",
        "Residential - Domestic;|House in EP/Rural Area;",
        "Residential - Domestic;|House On Small Lot;",
        "Residential - Domestic;|Landing (Residential - Domestic);",
        "Residential - Domestic;|Non-Compliant With House Code;",
        "Residential - Domestic;|Outdoor Lighting;",
        "Residential - Non-Domestic;|Aged Care Accommodation (Multiple Dwelling);",
        "Residential - Non-Domestic;|Aged Care Accommodation (Multi-unit Dwelling);",
        "Residential - Non-Domestic;|Aged Care Accommodation;",
        "Residential - Non-Domestic;|Caravan Park;",
        "Residential - Non-Domestic;|Caretakers Flat;",
        "Residential - Non-Domestic;|Multi-Unit Dwelling;",
        "Residential - Non-Domestic;|Retirement Village (Multi-unit Dwelling);",
        "Residential - Non-Domestic;|Retirement Village;",
        "Residential - Non-Domestic;|Short Term Accommodation;",
        "Residential - Non-Domestic;|Single Unit Dwelling;",
        "Residential - Non-Domestic;|Special Needs (Multi-unit Dwelling);",
        "Sport, Recreation and Community Uses;|Camping Ground;",
        "Sport, Recreation and Community Uses;|Cemetery;",
        "Sport, Recreation and Community Uses;|Community Facilities;",
        "Sport, Recreation and Community Uses;|Education Purposes ;",
        "Sport, Recreation and Community Uses;|Education Purposes;",
        "Sport, Recreation and Community Uses;|Emergency Services;",
        "Sport, Recreation and Community Uses;|Indoor Sport and Recreation;",
        "Sport, Recreation and Community Uses;|Outdoor Sport and Recreation;",
        "Sport, Recreation and Community Uses;|Park;",
        "Sport, Recreation and Community Uses;|Youth Club;",
        "Superseded Planning Scheme;|Request to apply superseded planning scheme;",
        "Transport/Accessibility;|Awning Over Footpath ;",
        "Transport/Accessibility;|Awning Over Footpath;",
        "Transport/Accessibility;|Busway;",
        "Transport/Accessibility;|Landing (Transport/Accessibility);",
        "Transport/Accessibility;|Light Rail;",
        "Transport/Accessibility;|Railway Activities;",
        "Transport/Accessibility;|Road;",
        "BCC Compliance Assessment;",
        "Build Over or Near Stormwater;",
        "Build Over Sewer;",
        "Building Over or Near Stormwater;",
        "Commercial;",
        "Engineering;",
        "Environmentally Relevant Activities;",
        "Exemption Certificate;",
        "House;",
        "Industry;",
        "Natural Environment;",
        "Plan Sealing;",
        "Pollution;",
        "Reconfigure a Lot;",
        "Reconfiguration;",
        "Referral Agency for Building Work;",
        "Referral Agency;",
        "Residential - Domestic;",
        "Residential - Non-Domestic;",
        "Sport, Recreation and Community Uses;",
        "Superseded Planning Scheme;",
        "Transport/Accessibility;",
    ]
    return tags


def get_ipswich_tags() -> list:
    tags = [
        "Building Work Assessable Against the P/S;|Demolition, Relocation or Removal;",
        "Building Work Assessable Against the P/S;|New Building or Structure;",
        "Building Work Assessable Against the P/S;|Other Building Work;",
        "Building Work Assessable Against the P/S;|Repairs, Alterations or Additions;",
        "Commercial/Industrial Uses;|Adult Store;",
        "Commercial/Industrial Uses;|Agricultural Supplies Store;",
        "Commercial/Industrial Uses;|Bar;",
        "Commercial/Industrial Uses;|Brothel;",
        "Commercial/Industrial Uses;|Bulk Landscape Supplies;",
        "Commercial/Industrial Uses;|Business Use;",
        "Commercial/Industrial Uses;|Car Wash;",
        "Commercial/Industrial Uses;|Extractive Industry;",
        "Commercial/Industrial Uses;|Food and Drink Outlet;",
        "Commercial/Industrial Uses;|Funeral Parlour ;",
        "Commercial/Industrial Uses;|Garden Centre;",
        "Commercial/Industrial Uses;|Hardware and Trade Supplies;",
        "Commercial/Industrial Uses;|Health Care Service;",
        "Commercial/Industrial Uses;|High Impact Industry;",
        "Commercial/Industrial Uses;|Hotel;",
        "Commercial/Industrial Uses;|Low Impact Industry;",
        "Commercial/Industrial Uses;|Marine Industry;",
        "Commercial/Industrial Uses;|Market;",
        "Commercial/Industrial Uses;|Medium Impact Industry;",
        "Commercial/Industrial Uses;|Miscellaneous Industrial Activities;",
        "Commercial/Industrial Uses;|Office;",
        "Commercial/Industrial Uses;|Other Commercial/Industrial Use;",
        "Commercial/Industrial Uses;|Outdoor Sales;",
        "Commercial/Industrial Uses;|Research and Technology Industry;",
        "Commercial/Industrial Uses;|Sales office;",
        "Commercial/Industrial Uses;|Service Industry;",
        "Commercial/Industrial Uses;|Service Station;",
        "Commercial/Industrial Uses;|Shop;",
        "Commercial/Industrial Uses;|Shopping Centre;",
        "Commercial/Industrial Uses;|Showroom;",
        "Commercial/Industrial Uses;|Special Industry;",
        "Commercial/Industrial Uses;|Transport Depot;",
        "Commercial/Industrial Uses;|Veterinary  Service;",
        "Commercial/Industrial Uses;|Warehouse;",
        "Commercial/Industrial Uses;|Wholesale Nursery;",
        "Operational Works - Civil;|Detailed Design Signalised Intersections;",
        "Operational Works - Civil;|Earthworks;",
        "Operational Works - Civil;|Other Operational Works - Civil;",
        "Operational Works - Civil;|Prescribed Tidal Work;",
        "Operational Works - Civil;|Roadworks;",
        "Operational Works - Civil;|Stormwater Drainage;",
        "Operational Works - Civil;|Stormwater Quality;",
        "Operational Works - Civil;|Stormwater Quantity;",
        "Operational Works - Electrical;|Electrical Reticulation;",
        "Operational Works - Electrical;|Other Operational Works - Electrical;",
        "Operational Works - Electrical;|Rate 3 Streetlighting;",
        "Operational Works - Environment;|Bushland Management Plan;",
        "Operational Works - Environment;|Environmental Management Plan;",
        "Operational Works - Environment;|Erosion and Sediment Control;",
        "Operational Works - Environment;|Fauna Management Plan;",
        "Operational Works - Environment;|Other Operational Works - Environment;",
        "Operational Works - Environment;|Vegetation Assessment Plan;",
        "Operational Works - Environment;|Vegetation Clearing;",
        "Operational Works - Environment;|Vegetation Management Plan;",
        "Operational Works - Landscaping;|Landscape Works - Internal;",
        "Operational Works - Landscaping;|Landscape Works in Park;",
        "Operational Works - Landscaping;|Landscape Works in Streetscape;",
        "Operational Works - Landscaping;|Other Operational Works - Landscaping;",
        "Operational Works - Other;|Other Operational Works;",
        "Operational Works - Other;|Signage;",
        "Other Uses;|Air Service;",
        "Other Uses;|Cemetery;",
        "Other Uses;|Child Care Centre;",
        "Other Uses;|Community Care Centre;",
        "Other Uses;|Community Use;",
        "Other Uses;|Crematorium;",
        "Other Uses;|Detention Facility;",
        "Other Uses;|Educational Establishment;",
        "Other Uses;|Emergency Services;",
        "Other Uses;|Environment Facility;",
        "Other Uses;|Hospital;",
        "Other Uses;|Landing;",
        "Other Uses;|Major Electricity Infrastructure;",
        "Other Uses;|Nature Based Tourism;",
        "Other Uses;|Other Undefined Use;",
        "Other Uses;|Outstation;",
        "Other Uses;|Parking Station;",
        "Other Uses;|Place of Worship;",
        "Other Uses;|Renewable Energy Facility;",
        "Other Uses;|Substation;",
        "Other Uses;|Telecommunications Facility;",
        "Other Uses;|Temporary Use;",
        "Other Uses;|Tourist Attraction;",
        "Other Uses;|Utility Installation;",
        "PDA Compliance Assessment - Civil;|Detailed Design Signalised Intersections;",
        "PDA Compliance Assessment - Civil;|Detailed Design Stormwater Quality;",
        "PDA Compliance Assessment - Civil;|Detailed Design Stormwater Quantity;",
        "PDA Compliance Assessment - Civil;|Flood Investigation Report;",
        "PDA Compliance Assessment - Civil;|Geotechnical Investigation Report;",
        "PDA Compliance Assessment - Civil;|Other PDA Condition;",
        "PDA Compliance Assessment - Civil;|Roadworks;",
        "PDA Compliance Assessment - Civil;|Stormwater Management Plan;",
        "PDA Compliance Assessment - Civil;|Traffic Management Plan/Traffic Safety Audit;",
        "PDA Compliance Assessment - Electrical;|Electrical Reticulation Design;",
        "PDA Compliance Assessment - Electrical;|Other PDA Compliance Assessment - Electrical;",
        "PDA Compliance Assessment - Electrical;|Rate 3 Streetlighting;",
        "PDA Compliance Assessment - Environment;|Bushland Management Plan;",
        "PDA Compliance Assessment - Environment;|Environmental Management Plan;",
        "PDA Compliance Assessment - Environment;|Fauna Management Plan;",
        "PDA Compliance Assessment - Environment;|Noise Management Plan;",
        "PDA Compliance Assessment - Environment;|Other PDA Compliance Assessment - Environment;",
        "PDA Compliance Assessment - Environment;|Vegetation Assessment Plan;",
        "PDA Compliance Assessment - Environment;|Vegetation Management Plan;",
        "PDA Compliance Assessment - Landscaping;|Landscape Works - Internal;",
        "PDA Compliance Assessment - Landscaping;|Landscape Works in Park;",
        "PDA Compliance Assessment - Landscaping;|Landscape Works in Streetscape;",
        "PDA Compliance Assessment - Landscaping;|Other PDA Compliance Assessment - Landscaping;",
        "PDA Infrastructure Offset;|Actual Offset;",
        "PDA Infrastructure Offset;|Other PDA Infrastructure Offset;",
        "PDA Infrastructure Offset;|Provisional Offset;",
        "PDA Preconstruction Submission - Civil;|Detailed Design Signalised Intersections;",
        "PDA Preconstruction Submission - Civil;|Earthworks;",
        "PDA Preconstruction Submission - Civil;|Other PDA Preconstruction Submission - Civil;",
        "PDA Preconstruction Submission - Civil;|Prescribed Tidal Work;",
        "PDA Preconstruction Submission - Civil;|Roadworks;",
        "PDA Preconstruction Submission - Civil;|Stormwater Drainage;",
        "PDA Preconstruction Submission - Civil;|Stormwater Quality;",
        "PDA Preconstruction Submission - Civil;|Stormwater Quantity;",
        "PDA Preconstruction Submission - Civil;|Vegetation Clearing;",
        "PDA Preconstruction Submission - Electrical;|Electrical Reticulation Design;",
        "PDA Preconstruction Submission - Electrical;|Other PDA Preconstruction Submission - Electrical;",
        "PDA Preconstruction Submission - Electrical;|Rate 3 Streetlighting;",
        "PDA Preconstruction Submission - Environment;|Bushland Management Plan;",
        "PDA Preconstruction Submission - Environment;|Environmental Management Plan;",
        "PDA Preconstruction Submission - Environment;|Erosion and Sediment Control;",
        "PDA Preconstruction Submission - Environment;|Fauna Management Plan;",
        "PDA Preconstruction Submission - Environment;|Other PDA Preconstruction Submission - Environment;",
        "PDA Preconstruction Submission - Environment;|Vegetation Assessment Plan;",
        "PDA Preconstruction Submission - Environment;|Vegetation Management Plan;",
        "PDA Preconstruction Submission - Landscaping;|Landscape Works - Internal;",
        "PDA Preconstruction Submission - Landscaping;|Landscape Works in Park;",
        "PDA Preconstruction Submission - Landscaping;|Landscape Works in Streetscape;",
        "PDA Preconstruction Submission - Landscaping;|Other PDA Preconstruction Submission - Landscaping;",
        "Reconfiguring a Lot;|Access Easement;",
        "Reconfiguring a Lot;|Boundary Realignment;",
        "Reconfiguring a Lot;|Subdivision by Lease;",
        "Reconfiguring a Lot;|Subdivision;",
        "Recreation/Entertainment Uses;|Club;",
        "Recreation/Entertainment Uses;|Entertainment Use;",
        "Recreation/Entertainment Uses;|Function Facility;",
        "Recreation/Entertainment Uses;|Hotel;",
        "Recreation/Entertainment Uses;|Indoor Sport and Recreation;",
        "Recreation/Entertainment Uses;|Major Sport, Recreation and Entertainment Facility;",
        "Recreation/Entertainment Uses;|Motor Sport Facility;",
        "Recreation/Entertainment Uses;|Nightclub Entertainment Facility;",
        "Recreation/Entertainment Uses;|Off-Road Motorcycling Facility;",
        "Recreation/Entertainment Uses;|Other Recreation/Entertainment Use;",
        "Recreation/Entertainment Uses;|Outdoor Sport and Recreation;",
        "Recreation/Entertainment Uses;|Park;",
        "Recreation/Entertainment Uses;|Theatre;",
        "Residential Uses;|Caretaker's Accommodation;",
        "Residential Uses;|Community Residence;",
        "Residential Uses;|Dual Occupancy (Relative's Accommodation);",
        "Residential Uses;|Dual Occupancy;",
        "Residential Uses;|Dwelling House;",
        "Residential Uses;|Dwelling Unit;",
        "Residential Uses;|Home Based Business;",
        "Residential Uses;|Multiple Dwelling;",
        "Residential Uses;|Non-Residential Workforce Accommodation;",
        "Residential Uses;|Other residential use;",
        "Residential Uses;|Party House;",
        "Residential Uses;|Relocatable Home Park;",
        "Residential Uses;|Residential Care Facility;",
        "Residential Uses;|Resort Complex;",
        "Residential Uses;|Retirement Facility;",
        "Residential Uses;|Rooming Accommodation;",
        "Residential Uses;|Rural Worker's Accommodation;",
        "Residential Uses;|Short-term accommodation;",
        "Residential Uses;|Tourist Park;",
        "Rural Uses;|Animal Husbandry;",
        "Rural Uses;|Animal Keeping;",
        "Rural Uses;|Aquaculture;",
        "Rural Uses;|Cropping;",
        "Rural Uses;|Intensive Animal Husbandry;",
        "Rural Uses;|Intensive Horticulture;",
        "Rural Uses;|Other Rural Use;",
        "Rural Uses;|Permanent Plantation;",
        "Rural Uses;|Roadside Stall;",
        "Rural Uses;|Rural Industry;",
        "Rural Uses;|Stock Sales Market;",
        "Rural Uses;|Winery;",
        "Signing of Subdivision Plan;|Building Format Plan;",
        "Signing of Subdivision Plan;|Easement;",
        "Signing of Subdivision Plan;|Other Plan Signing;",
        "Signing of Subdivision Plan;|Standard Format Plan;",
        "Building Work Assessable Against the P/S;",
        "Commercial/Industrial Uses;",
        "Operational Works - Civil;",
        "Operational Works - Electrical;",
        "Operational Works - Environment;",
        "Operational Works - Landscaping;",
        "Operational Works - Other;",
        "Other Uses;",
        "PDA Compliance Assessment - Civil;",
        "PDA Compliance Assessment - Electrical;",
        "PDA Compliance Assessment - Environment;",
        "PDA Compliance Assessment - Landscaping;",
        "PDA Infrastructure Offset;",
        "PDA Preconstruction Submission - Civil;",
        "PDA Preconstruction Submission - Electrical;",
        "PDA Preconstruction Submission - Environment;",
        "PDA Preconstruction Submission - Landscaping;",
        "Reconfiguring a Lot;",
        "Recreation/Entertainment Uses;",
        "Residential Uses;",
        "Rural Uses;",
        "Signing of Subdivision Plan;"
    ]
    return tags
